serviceAccount:
  create: true

pdb:
  enabled: true
  minAvailable: 1

hpa:
  enabled: false

app:
  image:
    repository: trow.kube-public:31000/elixir-app-template
    tag: latest
  labels: {}
  livenessProbe: {}
  readinessProbe: {}
  resources:
    requests:
      cpu: 20m
      memory: 80Mi
    limits:
      cpu: 50m
      memory: 200Mi

service:
  type: ClusterIP
  externalPort: 80
  annotations: {}
  labels: {}

serviceMonitor:
  enabled: false
  interval: "30s"
  path: /metrics
  selector: {}

migration:
  enabled: false

configMap:
  LOG_LEVEL: "debug"

secrets:
  SECRET_KEY_BASE: RKJnGRrqUKHwq8DcC3Ruiv/IpKPnguVQpVVQXaViiuOnnpBW7vFg4m/lwcFO/Xg5
  DATABASE_URL: ecto://eat_user:qwerty123@database-mysql/eat_db