app:
  image:
    repository: trow.kube-public:31000/elixir-app-template
    tag: latest
    pullPolicy: Always
  labels: {}
  livenessProbe: {}
  readinessProbe: {}
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

networkPolicy:
  enabled: true

service:
  type: ClusterIP
  externalPort: 80
  annotations: {}
  labels: {}

serviceMonitor:
  enabled: true
  interval: "30s"
  path: /metrics
  selector:
    release: prometheus

migration:
  enabled: true

configMap:
  LOG_LEVEL: "debug"

secrets:
  SECRET_KEY_BASE: RKJnGRrqUKHwq8DcC3Ruiv/IpKPnguVQpVVQXaViiuOnnpBW7vFg4m/lwcFO/Xg5
  DATABASE_URL: ecto://eat_user:qwerty123@database-mysql/eat_db