{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "app-template.fullname" . }}-migration
  labels:
    {{- include "app-template.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  activeDeadlineSeconds: 60
  template:
    metadata:
      name: {{ template "app-template.fullname" . }}-migration
    spec:
      restartPolicy: Never
      containers:
        - name: {{ template "app-template.fullname" . }}-migration
          image: trow.kube-public:31000/elixir-app-template:latest
          args: ["eval", "Domain.Migration.migrate"]
          {{- if or (.Values.configMap) (.Values.secrets) }}
          envFrom:
          {{- if .Values.configMap }}
            - configMapRef:
                name: {{ template "app-template.fullname" . }}
          {{- end }}
          {{- if .Values.secrets }}
            - secretRef:
                name: {{ template "app-template.fullname" . }}
          {{- end }}
          {{- end }}
{{- end }}
