{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "app-template.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "app-template.name" . }}
      tier: app
  ingress:
  - from: 
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          {{- include "app-template.egressLabel" . | nindent 10 }}
    ports:
      - port: {{ .Values.app.port | default 8080 }}
{{- end }}
