apiVersion: v1
kind: Service
metadata:
  name: {{ template "app-template.fullname" . }}
  labels:
    {{- include "app-template.labels" . | nindent 4 }}
  {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
  {{- end }}
{{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP"}}
  ports:
    - port: {{ .Values.service.externalPort | default 80 }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "app-template.name" . }}
    tier: app
    release: {{ $.Release.Name }}
