{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "app-template.fullname" . }}
  labels:
    {{- include "app-template.labels" . | nindent 4 }}
  {{- range $key, $value := .Values.serviceMonitor.selector }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "app-template.labels" . | nindent 6 }}
  endpoints:
  - port: {{ .Values.serviceMonitor.port | default "http-probe" }}
    path: {{ .Values.serviceMonitor.path }}
    interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
